# Generated by Django 5.0.4 on 2024-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(default=0, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='disponibilidade',
            field=models.IntegerField(),
        ),
    ]
